# Generated by Django 2.2.2 on 2019-06-25 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Extra_classe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profdisciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_professor', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='professor',
            name='nome_professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Extra_classe.Profdisciplina'),
        ),
    ]
