# Generated by Django 2.2.2 on 2019-06-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Extra_classe', '0002_auto_20190625_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_professor', models.CharField(max_length=100)),
                ('disciplina', models.CharField(max_length=100)),
                ('data', models.DateField(max_length=20)),
                ('hora', models.TimeField(max_length=20)),
            ],
        ),
    ]
