# Generated by Django 2.2.2 on 2019-06-26 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Extra_classe', '0003_atendimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='nome_professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Extra_classe.Profdisciplina'),
        ),
    ]
