# Generated by Django 2.2.2 on 2019-06-26 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Extra_classe', '0004_auto_20190626_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendimento',
            name='disciplina',
        ),
        migrations.AddField(
            model_name='atendimento',
            name='nome',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Extra_classe.Disciplina'),
            preserve_default=False,
        ),
    ]
