# Generated by Django 2.2.2 on 2019-06-26 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Extra_classe', '0005_auto_20190626_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atendimento',
            old_name='nome',
            new_name='disciplina',
        ),
    ]
