# Generated by Django 2.2.2 on 2019-06-27 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Extra_classe', '0007_aluno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='disponivel',
            new_name='Confirma',
        ),
    ]
