# Generated by Django 2.2.2 on 2019-06-27 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Extra_classe', '0008_auto_20190627_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='Confirma',
            new_name='Confirmar',
        ),
    ]
